version: "3.8"

services:
  app:
    container_name: app_cont
    build: .
    ports:
      - "1234:3000"
    environment:
      - DB_HOST=db_service
      - DB_USER=root
      - DB_PASSWORD=ZEns@r123  # Ensure this matches the DB service below
      - DB_NAME=school_management_system
    depends_on:
      - db
    networks:
      - school_network

  db:
    container_name: db_service
    build:
      context: ./db-app
    environment:
      - MYSQL_ROOT_PASSWORD=ZEns@r123 # Use the same password here
      - MYSQL_DATABASE=school_management_system
    # We remove MYSQL_USER=root here to prevent the crash you saw in logs
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - school_network

volumes:
  db_data:

networks:
  school_network:
    driver: bridge
